//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateChipsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int ActionID { get; set; }
        public string MarketSymbol { get; set; }
        public string BrokerGUID { get; set; }
        public string TimeStamp { get; set; }
        public string Action1 { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> ShareCount { get; set; }
        public Nullable<double> Investment { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> Budget { get; set; }
    }
}
