//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateChipsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public int Broker_ID { get; set; }
        public Nullable<decimal> Broker_NetWorth { get; set; }
        public Nullable<decimal> Broker_ProfitPerShare { get; set; }
        public Nullable<int> Broker_TotalShareCount { get; set; }
        public Nullable<decimal> Broker_NetWorthPerMarket { get; set; }
        public Nullable<int> Broker_Algorithm_Version { get; set; }
        public string Broker_GUID { get; set; }
        public Nullable<double> Broker_Setting_00 { get; set; }
        public Nullable<double> Broker_Setting_01 { get; set; }
        public Nullable<double> Broker_Setting_02 { get; set; }
        public Nullable<double> Broker_Setting_03 { get; set; }
        public Nullable<double> Broker_Setting_04 { get; set; }
        public Nullable<double> Broker_Setting_05 { get; set; }
        public Nullable<double> Broker_Setting_06 { get; set; }
        public Nullable<double> Broker_Setting_07 { get; set; }
        public Nullable<double> Broker_Setting_08 { get; set; }
        public Nullable<double> Broker_Setting_09 { get; set; }
        public Nullable<double> Broker_Setting_10 { get; set; }
        public Nullable<double> Broker_Setting_11 { get; set; }
        public Nullable<double> Broker_Setting_12 { get; set; }
        public Nullable<double> Broker_Setting_13 { get; set; }
        public Nullable<double> Broker_Setting_14 { get; set; }
        public Nullable<double> Broker_Setting_15 { get; set; }
        public Nullable<double> Broker_Setting_16 { get; set; }
        public Nullable<double> Broker_Setting_17 { get; set; }
        public Nullable<double> Broker_Setting_18 { get; set; }
        public Nullable<double> Broker_Setting_19 { get; set; }
        public Nullable<double> Broker_Setting_20 { get; set; }
        public Nullable<double> Broker_Setting_21 { get; set; }
        public Nullable<double> Broker_Setting_22 { get; set; }
        public Nullable<double> Broker_Setting_23 { get; set; }
        public Nullable<double> Broker_Setting_24 { get; set; }
        public Nullable<double> Broker_Setting_25 { get; set; }
        public Nullable<double> Broker_Setting_26 { get; set; }
        public Nullable<double> Broker_Setting_27 { get; set; }
        public Nullable<double> Broker_Setting_28 { get; set; }
        public Nullable<double> Broker_Setting_29 { get; set; }
        public Nullable<double> Broker_Setting_30 { get; set; }
        public Nullable<double> Broker_Setting_31 { get; set; }
        public Nullable<double> Broker_Setting_32 { get; set; }
        public Nullable<double> Broker_Setting_33 { get; set; }
        public Nullable<double> Broker_Setting_34 { get; set; }
        public Nullable<double> Broker_Setting_35 { get; set; }
        public Nullable<double> Broker_Setting_36 { get; set; }
        public Nullable<double> Broker_Setting_37 { get; set; }
        public Nullable<double> Broker_Setting_38 { get; set; }
        public Nullable<double> Broker_Setting_39 { get; set; }
        public Nullable<double> Broker_Setting_40 { get; set; }
        public Nullable<double> Broker_Setting_41 { get; set; }
        public Nullable<double> Broker_Setting_42 { get; set; }
        public Nullable<double> Broker_Setting_43 { get; set; }
        public Nullable<double> Broker_Setting_44 { get; set; }
        public Nullable<double> Broker_Setting_45 { get; set; }
        public Nullable<double> Broker_Setting_46 { get; set; }
        public Nullable<double> Broker_Setting_47 { get; set; }
        public Nullable<double> Broker_Setting_48 { get; set; }
        public Nullable<double> Broker_Setting_49 { get; set; }
        public Nullable<double> Broker_Setting_50 { get; set; }
        public Nullable<double> Broker_PercentReturn { get; set; }
    }
}
