//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateChipsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public int Market_ID { get; set; }
        public string MarketSymbol { get; set; }
        public string BrokerGUID { get; set; }
        public Nullable<double> MarketProfit { get; set; }
        public Nullable<int> MarketShareCount { get; set; }
        public Nullable<int> MarketDepth { get; set; }
        public Nullable<decimal> MarketProfitPerShare { get; set; }
        public Nullable<double> MarketPercentReturn { get; set; }
        public Nullable<int> MarketEndShareCount { get; set; }
    }
}
