//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateChipsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePoint
    {
        public int PricePoint_ID { get; set; }
        public Nullable<int> Market_ID { get; set; }
        public string Market_Name { get; set; }
        public byte[] PricePoint_Timestamp { get; set; }
        public Nullable<decimal> PricePoint_Open { get; set; }
        public Nullable<decimal> PricePoint_Close { get; set; }
        public Nullable<decimal> PricePoint_High { get; set; }
        public Nullable<decimal> PricePoint_Low { get; set; }
        public Nullable<int> PricePoint_Buy { get; set; }
        public Nullable<int> PricePoint_Sell { get; set; }
        public Nullable<int> PricePoint_SellAll { get; set; }
        public Nullable<int> PricePoint_SellSplit { get; set; }
    }
}
