//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateChipsWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int SummaryID { get; set; }
        public string MarketSymbol { get; set; }
        public string Timestamp { get; set; }
        public Nullable<int> BuyCount { get; set; }
        public Nullable<int> SellCount { get; set; }
        public Nullable<int> ActionCount { get; set; }
        public Nullable<double> AverageProfitPerShare { get; set; }
        public Nullable<double> Margin { get; set; }
        public Nullable<bool> BetterThanMargin { get; set; }
        public Nullable<double> AverageProfit { get; set; }
    }
}
